import '@/app/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from "./providers";
import getIntl from "@/components/intl";
import {ServerIntlProvider} from "@/components/ServerIntlProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: { children: React.ReactNode }) {
    const intl = await getIntl();

    return (
        <html lang={intl.locale}>
        <body>
        <ServerIntlProvider messages={intl.messages} locale={intl.locale}>
            <Providers>
                {children}
            </Providers>
        </ServerIntlProvider>
        </body>
        </html>
    )
}
